title: i Think ...
author:
  name: poolvos

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  A home for my alternative facts.

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings
minima:
  skin: auto
  # Generate social links in footer.  
  social_links:
    - { platform: github, user_url: "https://github.com/AdriaanKuipers/AdriaanKuipers.github.io/discussions/" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
# header_pages:
#   - about.md

show_excerpts: true
