title: i Think ...
author: poolvos
email: blog@poolvos.se
description: >-
  A home for my alternative facts.
  
# social links
github_username:  AdriaanKuipers
rss: rss

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"
